version: "3"

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /home/node_modules
      - ./front:/home/

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - /home/node_modules
      - ./back:/home/

